// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvnb2LIy8Pv8IcVRK8Yb8dK1y30DoyIy4',
    appId: '1:380472960221:web:46b28832d1c65ab4e8e734',
    messagingSenderId: '380472960221',
    projectId: 'misosirubot-bb1e6',
    authDomain: 'misosirubot-bb1e6.firebaseapp.com',
    storageBucket: 'misosirubot-bb1e6.appspot.com',
    measurementId: 'G-ERH0YDM6WF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDD8SOIX7DexQK-5pqW30x1t9Y56fC3Ms',
    appId: '1:380472960221:android:9d922be638fbdf63e8e734',
    messagingSenderId: '380472960221',
    projectId: 'misosirubot-bb1e6',
    storageBucket: 'misosirubot-bb1e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCjeerfdjY3Neql11KBim8of8_TLVaIu8',
    appId: '1:380472960221:ios:2a6d9349ae8ee64be8e734',
    messagingSenderId: '380472960221',
    projectId: 'misosirubot-bb1e6',
    storageBucket: 'misosirubot-bb1e6.appspot.com',
    iosClientId: '380472960221-lehap7c3qvvuk0al44dvr6gn4pj5slnu.apps.googleusercontent.com',
    iosBundleId: 'com.example.misobot',
  );
}
